# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GMLViewer
                                 A QGIS plugin
 GML Viewer for Czech DTM
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-10-27
        copyright            : (C) 2024 by Your Name
        email                : your.email@domain.com
        git sha              : $Format:%H$
 ***************************************************************************/
"""

def classFactory(iface):
    """Load GMLViewer class from file GMLViewer.
    
    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    from .gml_viewer import GMLViewer
    return GMLViewer(iface)