# -*- coding: utf-8 -*-
"""
/***************************************************************************
 qgis-jvf-dtm-plugin
                                 A QGIS plugin
 GML Viewer for Czech JVF DTM (Digital Technical Map)
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-08-23
        copyright            : (C) 2025 by Maps Geeks - Petr Barandovski and Linda Karlovska
        email                : petr.barandovski@gmail.com, linda.karlovska@seznam.cz
        git sha              : $Format:%H$
 ***************************************************************************/
"""

def classFactory(iface):
    """Load plugin.
    
    :param iface: QGIS interface.
    :type iface: QgsInterface
    """
    from .jvf_dtm_viewer import JVFDTMViewer
    return JVFDTMViewer(iface)
